version: '3.3'

services:
  postgres:
    image: postgres:12
    volumes:
      - .:/app
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: app
      POSTGRES_DB: app
      TZ: UTC
    ports:
      - 5432:5432
